# Generated by Django 4.1.13 on 2024-05-15 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app_for_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
