# Generated by Django 4.1.13 on 2024-05-27 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('company_email', models.EmailField(default='xyz@gmail.com', max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('company_schedule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('employee_role', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('skills', models.JSONField()),
                ('password', models.CharField(default='ajay', max_length=50)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app_for_project.company')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_email', models.EmailField(max_length=254)),
                ('requester_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(default=datetime.time(9, 0))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('number_of_slots', models.IntegerField()),
                ('available', models.BooleanField()),
                ('employee_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app_for_project.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app_for_project.user')),
                ('employee_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app_for_project.employee')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app_for_project.schedule')),
            ],
        ),
    ]
